import User from "../models/user.model";
import Material from "../models/material.model";
import Chat from "../models/chat.model";
import Quiz from "../models/quiz.model"
import Flashcard from "../models/flashCard.model";
import extractTextFromFile from "../services/file.service";
import { getYoutubeTranscript } from "../services/youtube.service";
import { generateFlashCards, generateResponse, quizGenerator, regenerateQuizzes } from "../services/gemini.service";
import {updateUserStreak, CurrentUserStreak } from "../services/streak.service";
import type {Request,Response,NextFunction} from "express"
interface CustomError extends Error {
  status?: number,
  statusCode?: number
}
export const uploadFile = async (req: Request, res: Response, next: NextFunction) => {
    if(!req.file){
      const error=new Error("No file uploaded") as CustomError
      error.status=400
      return next(error)
    }
    console.log(req.file)
    try{
       if (!req.user || !req.user._id) {
          const error = new Error("User information is missing") as CustomError;
          error.status = 401;
          return next(error);
        }
        const freeUsageLimit=2;
        const user= await User.findById(req.user._id);
        if(!user){
          const error=new Error("User not found") as CustomError;
          error.status=404;
          return next(error);
        }
        const {freeUsageCount}=user;
        if(!user.apiKey){
          if(freeUsageCount >= freeUsageLimit){
          const error=new Error("Free usage limit reached. Please enter your own Gemini API Key.") as CustomError;
          error.status=403;
          return next(error);
        }
        }

        const extractedText = await extractTextFromFile(req.file.buffer, req.file.mimetype);
        console.log(`Extracted text length: ${extractedText.text.length} characters`);
        const response = await generateResponse(`Hey Gemini, summarize the following text in a concise manner: ${extractedText.text}`,user.apiKey || undefined) ;
        const parsedResponse=JSON.parse(response);
        console.log(`[Gemini Summary] ${response.length} characters`);
        const userId = req.user._id;
        let newT;
        let summary;
        parsedResponse.map((item:{summary:String, title:String})=>{
          newT=item.title;
          summary=item.summary;
        })
        
        const newMatrial=new Material({
          materialType:"file",
          title:req.file.originalname,
          originalText:extractedText.text,
          userId:req.user._id,
          materialTitle:newT,
          summary,
        })
         if(!newMatrial){
          const error=new Error("Failed to save material to database") as CustomError
          error.status=500;
          throw error;
        }
        await newMatrial.save();
        await updateUserStreak(userId as any);
        if(!summary){
            const error= new Error("Failed to generate summary for the uploaded file") as CustomError;
            error.status=500;
            throw error
        }
        const flashcardResponse=await generateFlashCards(summary || "", user.apiKey || undefined);
        if(!flashcardResponse || flashcardResponse.length===0){
          console.log("[Echo Learn] No flashcards generated by Gemini.")
        }
        else{
        await Flashcard.insertMany(
          flashcardResponse.map((flashcard:any)=>({
            ...flashcard,
            userId,
            materialId:newMatrial._id,
          }))
        )}
        user.freeUsageCount += 1;
        await user.save();
        res.json({ response:summary, materialId:newMatrial._id });
    }
    catch(error){
        const customError = error as CustomError;
        if (customError.status) {
            return next(customError);
        }
        else{
            const err = new Error("Failed to process request: " + (error instanceof Error ? error.message : "Unknown error")) as CustomError;
            err.status = 500;
            return next(err);
        }
    }
}
export const uploadLink = async (req: Request, res: Response, next: NextFunction) => {
  const { link } = req.body;
  console.log(`\n[API CALL] /api/uploads/link received URL: ${link}`);

  if (!link){
    const error=new Error("No link provided") as CustomError
    error.status=400
    return next(error)
  }
  
  try {
     if(!req.user || !req.user._id){
      const error=new Error("User information is missing") as CustomError
      error.status=401;
      throw error
    }
    const userId=req.user._id;
    const freeUsageLimit=3;
    const user= await User.findById(userId)
    if(!user){
      const error= new Error("user info is not found") as CustomError;
      error.status=404;
      return next(error);
    }
  const freeUsageCount=user.freeUsageCount
  if(!user.apiKey){
    if(freeUsageCount >= freeUsageLimit){
      const error=new Error("Free usage limit reached. Please enter your own Gemini API Key.") as CustomError;
      error.status=403;
      return next(error);
    }
  }
    const transcript = await getYoutubeTranscript(link);
    if (!transcript || transcript.length < 10) {
      const error=new Error("The video doesn't have a transcript or the transcript was empty or too short.") as CustomError
      error.status=404
      return next(error)
    }
    const sumamrizedResponse = await generateResponse(`Hey Gemini, summarize the following YouTube transcript in a concise manner: ${transcript}`, user.apiKey || undefined);
    const parsedResponse=JSON.parse(sumamrizedResponse);
   
    let newT;
    let summary;
    parsedResponse.map((item:{summary:String, title:String})=>{
      newT=item.title;
      summary=item.summary;
    })
  
    const newMatrial= new Material({
        materialType:"link",
        title:newT || "YouTube Video",
        originalText:transcript,
        materialTitle:newT,
        summary:summary,
        userId
    })
    await newMatrial.save();
    if(!newMatrial){
      console.log("[Echo Learn] Failed to save material to database")
      const error=new Error("Failed to save material to database") as CustomError
      error.status=500;
      throw error;
    }
    if(!summary){
      console.log("[Echo Learn] Failed to generate summary for the provided link.")
      const error= new Error("Failed to generate summary for the provided link") as CustomError;
      error.status=500;
      throw error
    }
    const flashcardResponse=await generateFlashCards(summary || "", user.apiKey || undefined)
    await Flashcard.insertMany(
          flashcardResponse.map((flashcard:any)=>({
            ...flashcard,
            userId,
            materialId:newMatrial._id,
          }))
        )
        
    user.freeUsageCount += 1;
    await user.save();
    res.json({ transcript, response:summary ,MaterialId:newMatrial._id});
    console.log(`[SUCCESS] Transcript sent to EchoLearn frontend.`);
    await updateUserStreak(userId as any);
  } catch (err: any) {
    return next(err);
  }
};
export const continueConversation = async (req: Request, res: Response, next: NextFunction) => {
    const {materialId,userMessage}=req.body
    const material=await Material.findById(materialId)
    if(!material){
        const error=new Error("Material not found") as CustomError
        error.status=404
        return next(error)
    }
    if(!req.user || !req.user._id){
      const error=new Error("User information is missing") as CustomError
      error.status=401;
      throw error
    }
    const userId=req.user._id;
    const newChat= new Chat({
      userId,
      materialId,
      message:[{
        role:"user",
        text:userMessage,
      }]
    })
    await newChat.save();
   const messages=await Chat.find({materialId}).sort({ timeStamp: 1 })
   const systemMessage=messages.map(mssg=>(
    {
        role:mssg?.message?.[0]?.role || "user",
        content:mssg?.message?.[0]?.text || ""
    }
   )).slice(-10)
    const conversationHistory:{role: string; content: string}[] = [
        { role: "system", content: "You are a helpful assistant that provides information based on the provided material." },
        { role: "user", content: `Here is the material for reference: ${material.summary}` },
    ];
    conversationHistory.push(...systemMessage);
    const prompt = conversationHistory.map(msg => `${msg.role}: ${msg.content}`).join('\n');
    const response = await generateResponse(prompt, req.user.apiKey || undefined);
    const newAIChat = new Chat({
      userId:req.user._id,
      materialId,
      message:[
        {
          role:"model",
          text:response,
        }
      ]
    })
    await newAIChat.save();
    await updateUserStreak(userId as any);
    res.json({ response });
}
export const getUserMaterials = async (req: Request, res: Response, next: NextFunction) => {
   try{
    if(!req.user || !req.user._id){
      const error= new Error("Missing user information") as CustomError;
      error.status=401;
      throw error
    }
    const materials=await Material.find({userId:req.user._id}).sort({timestamps:-1})
    console.log(`[Echo Learn] Retrieved ${materials.length} materials for user ${req.user._id}`);
    res.json({ materials });
   } catch(error){
    next(error);
   }
}
export const deleteMaterial = async (req: Request, res: Response, next: NextFunction) => {
  try{
    const materialId=req.params.id;
    if(!materialId){
      throw new Error("Material ID is required") as CustomError
    }
    const deletedMaterial=await Material.findByIdAndDelete(materialId);
    if(!deletedMaterial){
      const error=new Error("something went wrong deleting the material") as CustomError
      error.status=500;
      throw error
    }
     
      await Chat.deleteMany({materialId});
      await Flashcard.deleteMany({materialId});
      await Quiz.deleteMany({materialId: materialId as any});
    res.json({message:"material is deleted"})
  }catch(err){
    next(err)
  }
}
export const getMaterialById = async (req: Request, res: Response, next: NextFunction) => {
  try{
    const {id}=req.params;
    if(!id){
      const error=new Error("Material ID is required") as CustomError
      error.status=400;
      throw error
    }
    const material=await Material.findById(id);
    if(!material){
      const error=new Error("Material not found") as CustomError
      error.status=404;
      throw error;
    }
    const chats=await Chat.find({materialId:id}).sort({timeStamp:1})
    res.json({ material, chats });
  }catch(error){
    next(error);
  }
}
export const generateQuizzes = async (req: Request, res: Response, next: NextFunction) => {
  try{
   const {id}=req.params;
   if(!req.user || !req.user._id){
     const error= new Error("user information is not found") as CustomError;
     error.status=401;
     throw error;
   }
   const userId=req.user._id;

   if(!id){
    const error=new Error("Material Id is Missing") as CustomError;
    error.status=400;
    throw error;
   }
   // Check if we already generated quizzes for this material
   const existingQuizzes = await Quiz.find({ materialId: id as any });
   if (existingQuizzes && existingQuizzes.length > 0) {
     return res.json({ quizzes: existingQuizzes });
   }
   const material=await Material.findById(id);
   if(!material){
    const error=new Error("Material not found") as CustomError;
    error.status=404;
    throw error;
   }
  
   const generatedQuizzes=await quizGenerator(material.summary, req.user.apiKey || undefined);
   const quizzes = await Quiz.insertMany(
    generatedQuizzes.map((quiz: any)=>({
      ...quiz,
      userId,
      materialId:id,
    }))
   );
 
   res.json({ quizzes });
  }catch(err){
    next(err);
  }
}
export const regenerateQuizzesAsync = async (req: Request, res: Response, next: NextFunction) => {
  try{
    const {id}=req.params;
    if(!req.user || !req.user._id){
      const error=new Error("user information is missing") as CustomError;
      error.status=401
      throw error
    }
    const userId=req.user._id
    if(!id){
      const error=new Error("Material Id is missing") as CustomError;
      error.status=400;
      throw error;
    }
    const material=await Material.findById(id)
    if(!material){
      const error=new Error("material is not found") as CustomError;
      error.status=404;
      throw error
    }
    let generatedQuizzes;
    const existingQuizzes=await Quiz.find({materialId:id as any})
    if(!existingQuizzes || existingQuizzes.length===0){
      generatedQuizzes= await quizGenerator(material.summary, req.user.apiKey || undefined)
    }else{
      const usefullData=existingQuizzes.map((quiz:any)=>(
        {question:quiz.question,
         options:quiz.options,
         correctAnswer:quiz.correctAnswer,
        }
      ))
      generatedQuizzes=await regenerateQuizzes(material.summary,usefullData, req.user.apiKey || undefined)
    }
    const quizzes=await Quiz.insertMany(
      generatedQuizzes.map((quiz:any)=>({
        ...quiz,
        userId,
        materialId:id,
      })   
    ))
    await updateUserStreak(userId as any);
    res.json({quizzes})
  }catch(error){
   next(error)
}}
export const getFlashcardsForReview = async (req: Request, res: Response, next: NextFunction) => {
  try{
  if(!req.user || !req.user._id){
    const error=new Error("user info is missing") as CustomError;
    error.status=401;
    throw error;
  }
  const userId=req.user._id;
  const endOfDay = new Date();
  endOfDay.setHours(23, 59, 59, 999);

  const flashcards=await Flashcard.find({userId,nextReviewDate:{ $lte: endOfDay }}).limit(20);
  if(!flashcards){
    const error=new Error("No flashcards are due for review") as CustomError;
    error.status=404;
    throw error;
  }
  const flashcardsToReturn=flashcards.map(flashcard=>({
  _id:flashcard._id,
  materialId:flashcard.materialId,
  front:flashcard.front,
  back:flashcard.back
  }))
  res.json({flashcards:flashcardsToReturn})
}catch(error){
  next(error)
}
};
export const updateFlashcardReview = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { id } = req.params;
    const { difficultyLevel } = req.body;
    if (!req.user || !req.user._id) {
      const error = new Error("User information is missing") as CustomError;
      error.status = 401;
      throw error;
    }
    const flashcard = await Flashcard.findById(id);
    if (!flashcard) {
      const error = new Error("Flashcard not found") as CustomError;
      error.status = 404;
      throw error;
    }
    const userId=req.user._id
    // Convert difficulty -> SM-2 quality score
    let quality = 0;
    if (difficultyLevel === "again") quality = 1;
    if (difficultyLevel === "hard") quality = 2;
    if (difficultyLevel === "good") quality = 4;
    if (difficultyLevel === "easy") quality = 5;
    let { repetitionCount, interval, easeFactor } = flashcard;
    // SM-2 Algorithm
    if (quality < 3) {
      repetitionCount = 0;
      interval = 1;
    } else {
      repetitionCount += 1;
      if (repetitionCount === 1) {
        interval = 1;
      } else if (repetitionCount === 2) {
        interval = 6;
      } else {
        interval = Math.round(interval * easeFactor);
      }
    }
    easeFactor =
      easeFactor +
      (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
    if (easeFactor < 1.3) {
      easeFactor = 1.3;
    }
    const nextReviewDate = new Date();
    nextReviewDate.setDate(nextReviewDate.getDate() + interval);
    flashcard.difficultyLevel = difficultyLevel;
    flashcard.repetitionCount = repetitionCount;
    flashcard.interval = interval;
    flashcard.easeFactor = easeFactor;
    flashcard.nextReviewDate = nextReviewDate;
    await flashcard.save();
    await updateUserStreak(userId as any);
    res.json({message:"Flashcard review updated successfully"});
  } catch (error) {
    next(error);
  }
};
export const getUserStreak = async (req: Request, res: Response, next: NextFunction) => {
  try{
    if(!req.user || !req.user._id){
      const error=new Error("User information is missing") as CustomError;
      error.status=401;
      throw error
    } 
    const userId=req.user._id;
    await CurrentUserStreak(userId as any);
    const user=await User.findById(userId)
    res.json({currentStreak:user?.currentStreak})
  }catch(error){
    next(error)
  }
}
export const uploadReminderSettings= async(req:Request ,res:Response ,next:NextFunction)=>{
    try{
      if(!req.user || !req.user._id){
        const error=new Error("Missing user information") as CustomError;
        error.status=401;
        throw error
      }
      const updateField:{streakReminderEnabled?:boolean; reminderHour?:number; reminderMinute?:number; timezone?:string}={}
    
      const {reminderHour,reminderMinute,timezone}=req.body;
      const streakReminderEnabled=req.body.streakReminders

      if(streakReminderEnabled !== undefined) updateField.streakReminderEnabled = streakReminderEnabled;
      if(reminderHour !== undefined) updateField.reminderHour = reminderHour;
      if(reminderMinute !== undefined) updateField.reminderMinute = reminderMinute;
      if(timezone !== undefined) updateField.timezone = timezone;
      console.log("Updating user settings with:", updateField);
      const updatedUser=await User.findByIdAndUpdate(req.user._id, { $set: updateField }, { returnDocument: 'after' })
      if(!updatedUser){
        const error=new Error("Failed to update user settings") as CustomError;
        error.status=500;
        throw error;
      }
      res.json({message:"Study reminder settings updated successfully."})
      console.log(updatedUser)
    }catch(error){
      next(error)
    }
}
export const updateAPIKey= async(req:Request ,res:Response ,next:NextFunction)=>{
    try{
      if(!req.user || !req.user._id){
        const error=new Error("Missing user information") as CustomError;
        error.status=401;
        throw error
      }
      console.log(req.body.apiKey)
      const user= await User.findByIdAndUpdate(req.user._id, { $set: { apiKey: req.body.apiKey } }, { returnDocument: 'after' })
      if(!user){
        const error=new Error("Failed to update API key") as CustomError;
        error.status=500;
        throw error;
      }
      
      res.json({message:"API key updated successfully."})
    }
    catch(err){
      next(err)
    }
    }