import { execFile } from "child_process";
import fs from "fs";
import path from "path";
import os from "os";

export function getYoutubeTranscript(link: string): Promise<string> {
  return new Promise((resolve, reject) => {
    // 1. Validate and Extract Video ID
    const videoIdMatch = link.match(/(?:v=|youtu\.be\/|shorts\/)([0-9A-Za-z_-]{11})/);
    if (!videoIdMatch) {
      return reject(new Error("Invalid YouTube link format."));
    }
    const videoId = videoIdMatch[1];

    // 2. Safe Pathing
    const tmpDir = os.tmpdir();
    const outputBase = path.join(tmpDir, `sub_${videoId}`);

    // Use environment variable for production, fallback to your local Windows path for dev
    const ytDlpPath = process.env.YTDLP_PATH || "C:\\tools\\yt-dlp\\yt-dlp.exe";

    // 3. Command arguments as an array (PREVENTS COMMAND INJECTION)
    const args = [
      "--skip-download",
      "--write-auto-subs",
      "--sub-format", "vtt",
      "--sub-lang", "en",
      "--js-runtimes", "node",
      // "--cookies-from-browser", "chrome+any", // Note: This might fail on a headless production server
      "-o", outputBase,
      link
    ];

    console.log(`\n[DEBUG 1] Starting yt-dlp for Video: ${videoId}`);
    
    execFile(ytDlpPath, args, (err: Error | null, stdout: string, stderr: string) => {
      if (stdout) console.log(`[yt-dlp STDOUT]: ${stdout.trim()}`);
      if (stderr) console.error(`[yt-dlp STDERR]: ${stderr.trim()}`);

      if (err) {
        console.error(`[DEBUG 2] Exec Error: ${err.message}`);
        return reject(new Error(`yt-dlp failed: ${err.message}`));
      }

      try {
        // 4. Find the generated file in the temp directory
        const files: string[] = fs.readdirSync(tmpDir);
        const subtitleFileName = files.find((f: string) => f.startsWith(`sub_${videoId}`) && f.endsWith(".vtt"));

        if (!subtitleFileName) {
          console.error(`[DEBUG 3] File search failed in ${tmpDir}`);
          return reject(new Error("No subtitles file was generated by yt-dlp."));
        }

        const subtitleFilePath = path.join(tmpDir, subtitleFileName);
        const rawContent = fs.readFileSync(subtitleFilePath, "utf8");
        console.log(`[DEBUG 4] File read successfully. Character count: ${rawContent.length}`);

        // 5. Clean AND Deduplicate (Fixes YouTube Roll-up Captions)
        const cleanText = rawContent
          .split("\n")
          .map((line: string) => line.replace(/<[^>]*>/g, "").trim()) // Remove HTML tags
          .filter((line: string) => {
            const isHeader = line.includes("WEBVTT") || line.includes("Kind:") || line.includes("Language:");
            const isTimestamp = line.includes("-->");
            return !isHeader && !isTimestamp && line !== "";
          })
          .reduce((acc: string[], currentLine: string) => {
            // Basic deduplication: only add the line if it's not identical to the last one
            if (acc.length === 0 || acc[acc.length - 1] !== currentLine) {
              acc.push(currentLine);
            }
            return acc;
          }, [])
          .join(" ")
          .replace(/\s+/g, " "); // Collapse multiple spaces

        // 6. Cleanup
        fs.unlinkSync(subtitleFilePath);
        console.log(`[DEBUG 5] Cleanup: Deleted ${subtitleFilePath}`);

        resolve(cleanText);

      } catch (innerErr: any) {
        console.error(`[DEBUG 6] Processing Error: ${innerErr.message}`);
        reject(innerErr);
      }
    });
  });
}