import { exec } from "child_process";
import fs from "fs";

/**
 * IMPROVED TRANSCRIPT FUNCTION WITH VERBOSE LOGGING
 */
export function getYoutubeTranscript(link: string): Promise<string> {
  return new Promise((resolve, reject) => {
    // 1. Extract Video ID to create a unique filename (prevents conflicts if 2 users use it at once)
    const videoIdMatch = link.match(/(?:v=|\/)([0-9A-Za-z_-]{11})/);
    const videoId = videoIdMatch ? videoIdMatch[1] : `temp_${Date.now()}`;
    const outputBase = `sub_${videoId}`;

    // 2. The Command
    // Added --quiet to reduce noise, but kept error reporting
    const command = `C:\\tools\\yt-dlp\\yt-dlp.exe --skip-download --write-auto-subs --sub-format vtt -o "${outputBase}" "${link}"`;

    console.log(`\n[DEBUG 1] Starting yt-dlp for Video: ${videoId}`);
    console.log(`[DEBUG 2] Executing Command: ${command}`);

    exec(command, (err, stdout, stderr) => {
      // 3. Log the Raw Output from the Terminal
      if (stdout) console.log(`[yt-dlp STDOUT]: ${stdout}`);
      if (stderr) console.error(`[yt-dlp STDERR]: ${stderr}`);

      if (err) {
        console.error(`[DEBUG 3] Exec Error: ${err.message}`);
        return reject(`yt-dlp failed: ${err.message}`);
      }

      try {
        // 4. yt-dlp appends the language code (e.g., sub_123.en.vtt)
        // We need to find the file that STARTS with our outputBase
        const files = fs.readdirSync(".");
        const subtitleFile = files.find(f => f.startsWith(outputBase) && f.endsWith(".vtt"));

        console.log(`[DEBUG 4] Directory Search. Looking for: ${outputBase}. Found: ${subtitleFile}`);

        if (!subtitleFile) {
          console.error(`[DEBUG 5] File search failed. Current files in root: ${files.slice(0, 5).join(", ")}...`);
          return reject("No subtitles file was generated by yt-dlp.");
        }

        // 5. Read and Clean
        const rawContent = fs.readFileSync(subtitleFile, "utf8");
        console.log(`[DEBUG 6] File read successfully. Character count: ${rawContent.length}`);

        const cleanText = rawContent
          .split("\n")
          .filter(line => {
            const isHeader = line.includes("WEBVTT") || line.includes("Kind:") || line.includes("Language:");
            const isTimestamp = line.includes("-->");
            const isPositioning = line.includes("<c>") || line.includes("align:");
            return !isHeader && !isTimestamp && !isPositioning && line.trim() !== "";
          })
          .map(line => line.replace(/<[^>]*>/g, "")) // Remove any remaining HTML tags like <c>
          .join(" ")
          .replace(/\s+/g, " ") // Collapse multiple spaces
          .trim();

        // 6. Cleanup
        fs.unlinkSync(subtitleFile);
        console.log(`[DEBUG 7] Cleanup: Deleted ${subtitleFile}`);

        resolve(cleanText);

      } catch (innerErr: any) {
        console.error(`[DEBUG 8] Processing Error: ${innerErr.message}`);
        reject(innerErr);
      }
    });
  });
}
